server:
  port: 80
  servlet:
    context-path: /
 
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  
  datasource:
    url: jdbc:mysql://34.64.176.193:3306/spring?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: spring
    password: bitc5600
    driver-class-name: com.mysql.cj.jdbc.Driver 
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        
